import type Anthropic from "@anthropic-ai/sdk";
import { anthropic, CLAUDE_MODEL } from "@/lib/anthropic";
import { prisma } from "@/lib/prisma";
import { getSettings } from "@/lib/settings";

const DRAFT_EMAIL_TOOL = {
  name: "draft_email",
  description: "Draft a single outreach email to one contact.",
  input_schema: {
    type: "object" as const,
    properties: {
      subject: { type: "string" },
      body: { type: "string" },
      claimsNotToMake: {
        type: "string",
        description:
          "What was deliberately left vague or unclaimed due to lack of evidence in the company/contact record.",
      },
    },
    required: ["subject", "body", "claimsNotToMake"],
  },
};

// Real, current research before drafting — without this the model can only
// go on whatever's in the (often thin/unknown) company record plus its own
// training knowledge, which has repeatedly produced wrong claims about a
// prospect's actual TikTok Shop status (see: Wild Rye).
const WEB_SEARCH_TOOL = {
  type: "web_search_20250305" as const,
  name: "web_search" as const,
  max_uses: 3,
};

const RESEARCH_INSTRUCTION = `Research requirement — do this BEFORE calling draft_email, not instead of it:
Use the web_search tool at least once to check the company's actual, current TikTok Shop status (e.g. search "[Company] TikTok Shop") — don't rely solely on the record below if its TikTok Shop status is thin/unknown, and don't rely on training knowledge, which can be stale. If a real monthly GMV or sales figure turns up, use it per the numbers rules. If you need a category-level or comparable-brand stat, one more search is fine (max 3 total). Once you've searched, call draft_email with your final draft — searching is not optional, but it also isn't the deliverable, don't stop after searching without drafting.`;

export const CLAIMS_DISCIPLINE = `Voice: casual, conversational, informed, observational, concise. The email should feel like "I work in this space, I noticed something relevant about your brand or category, and was curious whether this is on your radar" — not a cold-sales pitch. Never pushy, apologetic, overly scripted, or prescriptive.

Non-negotiable rules:
- Never fabricate a fact not present in the company/contact record: no invented GMV, margin, or COGS figures, and no "we know you need this" claims.
- Don't state a specific-sounding claim (e.g. "a handful of skincare brands have taken off on TikTok Shop") unless there's real basis for it in the record. When unsure, generalize instead ("brands in the space are exploring this") rather than invent a precise-sounding one.
- Numbers: never fabricate a number. Two things ARE allowed to use real numbers: (1) a competitor, comparable brand, or category-level stat about TikTok Shop, but only if it's genuinely researched/sourced, not invented or estimated to sound precise — keep this to ONE short sentence with one stat, never stack multiple data points or name multiple comparable brands, and write it in active voice ("brands generated $X" not "$X was generated by brands"); (2) a general, non-prospect-specific range statement like "we've seen TikTok Shop become a meaningful six and seven figure monthly revenue channel in a matter of months" — this is a claim about DGA's track record in general, not about this specific prospect. When neither a sourced stat nor that general range fits, use a plain industry-level estimate ("brands in the space are seeing real traction") rather than a fake-precise figure. Never state a number about the specific prospect's own business (their revenue, GMV, COGS, etc.) unless it's already in the record and they've shared it themselves. If the prospect is already on TikTok Shop and a real monthly GMV figure for them is genuinely known/researched, prefer that framing over generic proof points like follower counts or units sold — but never invent or round-estimate a GMV figure just to have one; if no real GMV figure is available, fall back to whatever real, specific detail is actually known instead.
- "Six and seven-figure" has no hyphen after "six" — write "six and seven-figure," never "six- and seven-figure."
- Capitalize category names wherever they appear (e.g. "Wellness and Supplements," "Outdoor Apparel," "Sports and Outdoors") — title case, even though the rest of the sentence around it is normal lowercase prose.
- Say "TikTok Shop" in full on first mention within an email; "Shop" or "the platform" are fine for later mentions in the same email, for variety, never for the first mention.
- Never say a brand is "already" on TikTok Shop or "live on" TikTok Shop — both read weak/vague. State the fact plainly instead: name the real GMV figure if known ("is doing $X in monthly GMV on TikTok Shop"), or just "is on TikTok Shop" if no figure is known.
- "We feel confident" is banned — write "We're confident" instead.
- "Further" is banned as a filler word ("scale further," "further on TikTok Shop") — cut it, the sentence works without it.
- Dollar figures: lowercase "k" and "m" (e.g. "$150k," "$2m"), never uppercase, and phrase as "$X in monthly GMV," not "$X monthly GMV."
- "Ahead of Q4" is fine for a scene-setting opener ("Ahead of Q4, I've been looking into..."), but for anything implying a deadline or timeframe for onboarding/deciding, use "going into Q4" instead — "ahead of" implies Q4 is still far off, and by the time these actually send it usually isn't.
- Greeting: "Hey [First name]," — not "Hi."
- Subject lines: prefer the literal format "[Brand] x DGA (TikTok Shop)" — short, plain, not a full sentence. Only deviate from that format if it would read awkwardly for a specific brand name.
- At most one question mark in the entire email body. One ask, asked once — never stack a second direct question (e.g. a category question plus a separate CTA question) even if both feel soft individually.
- One observation, stated plainly. Don't stack multiple points, don't build a case, don't explain the research or reasoning behind it in the email. Never prescribe a strategy, plan, or specific offer before discovery — the email opens a conversation, it doesn't pitch a solution.
- No unrelated analogies, stories, or "fun facts" as an opener.
- Never lecture or diagnose: no "you're missing this," "you should be doing X," or similar. We're observing something in the market, not grading their strategy.
- Never sound like an interrogation: avoid "Why aren't you doing this?" or "How is [Company] thinking about X?" — too forceful.
- Never use LinkedIn-style thought-leadership hooks: no "Unpopular opinion...", no contrarian framing, no obvious copywriting formula that reads scripted or spammy.
- Never hedge or apologize, and never hand the prospect a preemptive excuse not to answer. Banned patterns: "If it's not a priority, that's totally fine," "Just asking because...," "Not looking for anything here...," "Just flagging...," "No worries either way." Don't explain why we're asking — just ask.
- Never announce what the email isn't (e.g. "not a formal pitch, but..."). Write it so it doesn't feel like a pitch instead of saying so.
- Prefer observational phrasing — "I noticed," "I came across," "we're seeing" — over persuasive or salesy language. Avoid generic selling phrases: "happy to share what we're seeing work," "natural fit," "meaningful opportunity," "book a call."
- Question bank, when a question is used — varied so it doesn't read identically every time. It branches on TWO things: whether the brand is already on TikTok Shop (getting this right matters — a brand already live on TikTok Shop should never get a "have you considered getting on TikTok Shop" style question, it reads like you didn't do the research), and the contact's seniority, which only changes how the question ENDS. Rotate the ending across these, matched to the contact's role — don't reuse the same ending every time:
  - "...a priority for you?" (senior/economic buyer)
  - "...a priority for the team?" / "...a priority for the team to explore?" (junior/operational)
  - "...something you've explored?" / "...something the team has explored?"
  - "...a priority for [Company]?"
  - "...currently on [your/the team's] radar?" — the preferred ending specifically for the FIRST TOUCH when a real GMV figure is already being cited in that same email; save the "priority" endings above for later touches instead, don't stack both framings in the same email.
  - TTS-status branch for the rest of the question:
    - Not on TikTok Shop: "Is scaling on TikTok Shop [ending]" — senior contacts can drop a softer "or on your radar" hedge some of these endings would otherwise carry; junior contacts can keep it.
    - Already on TikTok Shop, GMV known: "Is scaling to [the real known monthly GMV figure, or 'six and seven-figure' if that's the framing being used] monthly GMV [ending]"
    - Already on TikTok Shop, GMV not known: "Is scaling on TikTok Shop [ending]" (never "scaling further," "further" is banned, see above)
  - Timing in the question itself: "going into Q4," not "ahead of Q4" (see the Q4-phrasing rule above).
  - Later touches, not on TTS: "Is scaling on TikTok Shop a priority for the team going into the holiday season?"
  - Later touches, already on TTS: "Is scaling on TikTok Shop something the team's been considering?" or "Is this currently a priority for [you/the team/Company] to explore?"
  - Do not use: "Has [Company] looked seriously at TikTok Shop yet?" or "How is [Company] thinking about TikTok Shop?" — too direct, demands a strategic answer instead of an easy yes/no.
- Do not literally name the contact's title or decision role in the email body (never write "as the Ecommerce Manager..." or "given your role in...").
- Avoid em dashes (—). If a sentence would naturally use one, either rewrite it as two sentences or use a single hyphen (-) instead. Do not overuse hyphens as a substitute either — prefer plain sentence structure.
- Respect multi-thread sequencing: a functional owner gets the primary technical/operational pitch; a routing/champion contact gets a lighter "who owns this decision" message; the economic buyer is only approached directly when warranted (large deal, no response from others, or a small/founder-led company where the founder is the economic buyer).
- In claimsNotToMake, list anything you deliberately left vague or unclaimed due to lack of evidence.`;

// Only reference Q4/Black Friday when it's actually seasonally true, so the
// framing doesn't go stale as the calendar moves past this launch window.
function getSeasonalFramingInstruction(now = new Date()): string {
  const month = now.getMonth() + 1; // 1-12
  if (month >= 7 && month <= 9) {
    return `Mention that brands are actively getting set up on TikTok Shop ahead of Q4 and Black Friday — it's currently ${now.toLocaleString("en-US", { month: "long" })}, so this framing is timely.`;
  }
  if (month >= 10 && month <= 12) {
    return `Mention that a lot of brands are getting set up on TikTok Shop right now for Black Friday and the Q4 push — it's currently ${now.toLocaleString("en-US", { month: "long" })}, so this is happening now, not "coming up."`;
  }
  return `Skip the Q4/Black Friday framing entirely — it's currently ${now.toLocaleString("en-US", { month: "long" })}, too far past that season to reference it naturally. Use a general "brands are adopting TikTok Shop this year" framing instead if a why-now beat is needed at all.`;
}

function findDraftToolUse(content: Anthropic.ContentBlock[]) {
  return content.find(
    (block): block is Anthropic.ToolUseBlock => block.type === "tool_use" && block.name === "draft_email"
  );
}

export async function callDraftTool(systemPrompt: string, userPrompt: string) {
  const system = `${systemPrompt}\n\n${RESEARCH_INSTRUCTION}`;
  const messages: Anthropic.MessageParam[] = [{ role: "user", content: userPrompt }];

  const first = await anthropic.messages.create({
    model: CLAUDE_MODEL,
    max_tokens: 3000,
    system,
    tools: [WEB_SEARCH_TOOL, DRAFT_EMAIL_TOOL],
    // Can't force draft_email immediately — that would block the model from
    // searching first. "auto" lets it search, then draft; the system prompt
    // above is what actually mandates the research step.
    tool_choice: { type: "auto" },
    messages,
  });

  let toolUse = findDraftToolUse(first.content);

  // "auto" sometimes lets the model stop after searching (or run out of
  // max_tokens) without ever calling draft_email — the system prompt asks
  // for it but doesn't guarantee it. Force a second turn, tool_choice
  // pinned to draft_email, so it always finishes the job using whatever
  // research it already gathered in the transcript above.
  if (!toolUse) {
    messages.push({ role: "assistant", content: first.content });
    messages.push({
      role: "user",
      content:
        "Call draft_email now with your final draft, based on whatever research is above.",
    });

    const second = await anthropic.messages.create({
      model: CLAUDE_MODEL,
      max_tokens: 3000,
      system,
      tools: [DRAFT_EMAIL_TOOL],
      tool_choice: { type: "tool", name: "draft_email" },
      messages,
    });

    toolUse = findDraftToolUse(second.content);
  }

  if (!toolUse) throw new Error("Claude did not return a draft_email tool call.");

  return toolUse.input as { subject: string; body: string; claimsNotToMake: string };
}

export async function draftFirstEmail(
  contactId: string,
  feedbackNote?: string,
  autoTrigger = false
) {
  const contact = await prisma.contact.findUniqueOrThrow({
    where: { id: contactId },
    include: {
      company: true,
      emails: { orderBy: { createdAt: "desc" } },
    },
  });

  const settings = await getSettings();

  const draftingFeedback = await prisma.feedback.findMany({
    where: { scope: "drafting" },
    orderBy: { createdAt: "desc" },
    take: 25,
    select: { note: true },
  });

  const priorEmails = contact.emails;

  // Assigned once per contact and reused for the whole sequence, so
  // follow-ups stay consistent with whichever variant the first touch used.
  let variant: string | null = null;
  if (settings.abTestingEnabled) {
    variant = contact.variant;
    if (!variant) {
      variant = Math.random() < 0.5 ? "A" : "B";
      await prisma.contact.update({ where: { id: contactId }, data: { variant } });
    }
  }
  const variantHint =
    variant === "A" ? settings.abVariantAHint : variant === "B" ? settings.abVariantBHint : null;

  const firstTouchStructure = `First-touch structure, roughly 50-65 words total, hard cap 70. Write it as ONE flowing set of sentences, not a checklist of disconnected beats stitched together with connector phrases. Fit these beats into that budget:

1. Who we are — one short clause, and its shape depends on whether you have a real GMV figure to cite later in this same email (see step 2):
   - If you'll be citing a real, known monthly GMV figure for this prospect in step 2: keep this clause plain, no GMV claim — "I'm [name] - my team and I partner with TikTok to help identify and scale brands on TikTok Shop." (the specific number belongs in step 2/3, not duplicated here)
   - If you won't have a specific number to cite (not on TikTok Shop, or on it but no known GMV figure): include the general aspirational claim — "I'm [name] - my team and I partner with TikTok to help identify and scale brands to six and seven-figure monthly GMV on TikTok Shop."
   Paraphrase naturally, don't copy verbatim every time. Don't spell out "DGA" here (it's implied by the sender's email/signature).
2. Category + observation, one sentence: "Ahead of Q4, I've been looking closely at the [Category] category on the platform and noticed that [Company] [observation]." Capitalize the category name itself (e.g. "Wellness and Supplements," "Outdoor Apparel") even though the rest of the sentence is lowercase. ${getSeasonalFramingInstruction()} The observation MUST match their actual TikTok Shop status (given below) — three real cases, never blur them:
   - Not on TikTok Shop: "...noticed that [Company] isn't currently on Shop."
   - Already on TikTok Shop, real GMV figure genuinely known/sourced: state it directly — "...noticed that [Company] is doing $X in monthly GMV on Shop." Never invent or round-estimate this figure.
   - Already on TikTok Shop, no known GMV figure: keep it plain — "...noticed that [Company] is on Shop." Never say "already" or "live on," both read weak.
   - On TikTok Shop but status otherwise unclear/thin: keep it at the category level rather than guessing a status.
   ("Shop" here is fine even though it's the first use of that specific word — "TikTok Shop" was already said in full in step 1's clause, so this is really the second mention in the email.)
   Never default to "not on TikTok Shop" if the record shows otherwise — this has been wrong before when the record was thin instead of actually checked.
3. The ask — exactly one question from the question bank in the rules above, matched to which of the three cases above applied, and the only question mark in the email.`;

  const systemPrompt = `You are drafting outreach email copy for Dallas Global Agency's TikTok Shop brand-prospecting program.\n\n${CLAIMS_DISCIPLINE}\n\n${firstTouchStructure}\n\nStanding style feedback from the admin:\n${
    draftingFeedback.length > 0
      ? draftingFeedback.map((f) => `- ${f.note}`).join("\n")
      : "(none yet)"
  }`;

  const userPrompt = `Company: ${contact.company.name} (${contact.company.domain})
Hero SKU: ${contact.company.heroSku ?? "unknown"} ${contact.company.skuPrice ?? ""}
Archetype: ${contact.company.archetype ?? "unknown"}
Account thesis: ${contact.company.accountThesis ?? "none on file"}
COGS notes: ${contact.company.cogsNotes ?? "none on file"}
TikTok Shop status: ${contact.company.ttsStatus ?? "unknown"}

Contact: ${contact.name}, ${contact.title}
Decision role: ${contact.decisionRole}

${
  priorEmails.length > 0
    ? `Prior outreach history with this company:\n${priorEmails
        .map((e) => `- [step ${e.sequenceStep}, ${e.status}] Subject: ${e.subject}`)
        .join("\n")}`
    : "No prior outreach history with this company."
}

${feedbackNote ? `Quick note for this regeneration: ${feedbackNote}` : ""}
${variantHint ? `\nStanding personalization approach for this contact (variant ${variant}): ${variantHint}` : ""}

Draft the first outreach email (sequence step 0) to this contact. End with the closing "Best," — do not sign with a name or company, a signature block is appended automatically after your draft. Never sign off using the recipient's own name.`;

  const draft = await callDraftTool(systemPrompt, userPrompt);

  const shouldAutoApprove = autoTrigger && settings.autoApproveFirstEmails;
  const statusFields = shouldAutoApprove
    ? { status: "approved", approvedAt: new Date(), approvedBy: "auto" }
    : { status: "draft" };

  const existing = await prisma.email.findFirst({
    where: { contactId, sequenceStep: 0 },
  });

  if (existing) {
    return prisma.email.update({
      where: { id: existing.id },
      data: {
        subject: draft.subject,
        body: draft.body,
        claimsNotToMake: draft.claimsNotToMake,
        variant,
        ...statusFields,
      },
    });
  }

  return prisma.email.create({
    data: {
      contactId,
      sequenceStep: 0,
      subject: draft.subject,
      body: draft.body,
      claimsNotToMake: draft.claimsNotToMake,
      variant,
      ...statusFields,
    },
  });
}
