import { getSettings } from "@/lib/settings";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { updateSettings } from "./actions";

export default async function SettingsPage() {
  const settings = await getSettings();

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold tracking-tight">Settings</h1>
        <p className="text-sm text-neutral-500">
          These apply globally, across every company and sequence.
        </p>
      </div>

      <form action={updateSettings} className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle className="text-sm font-semibold">
              Automation — per pipeline step
            </CardTitle>
            <p className="text-xs text-neutral-500">
              Discovery and Prospecting are always manual — there&apos;s no
              scheduled trigger for either, you run them on demand. These
              toggles control the steps that can otherwise run without you.
            </p>
          </CardHeader>
          <CardContent className="max-w-lg space-y-4">
            <div className="flex items-start gap-2">
              <Checkbox
                id="autoDraftFirstEmails"
                name="autoDraftFirstEmails"
                defaultChecked={settings.autoDraftFirstEmails}
                className="mt-0.5"
              />
              <div>
                <Label htmlFor="autoDraftFirstEmails" className="font-normal">
                  Auto-draft first emails when contacts are selected
                </Label>
                <p className="text-xs text-neutral-500">
                  If off, drafting requires clicking &quot;Generate
                  Drafts&quot; on the company&apos;s drafting page instead of
                  starting automatically.
                </p>
              </div>
            </div>
            <div className="flex items-start gap-2">
              <Checkbox
                id="autoGenerateFollowUps"
                name="autoGenerateFollowUps"
                defaultChecked={settings.autoGenerateFollowUps}
                className="mt-0.5"
              />
              <div>
                <Label htmlFor="autoGenerateFollowUps" className="font-normal">
                  Auto-generate follow-up content when due (daily cron)
                </Label>
                <p className="text-xs text-neutral-500">
                  If off, the cron does nothing — draft follow-ups from the
                  Review Queue&apos;s &quot;Upcoming follow-ups&quot; list
                  instead, whenever you want.
                </p>
              </div>
            </div>
            <div className="flex items-start gap-2">
              <Checkbox
                id="autoApproveFirstEmails"
                name="autoApproveFirstEmails"
                defaultChecked={settings.autoApproveFirstEmails}
                className="mt-0.5"
              />
              <div>
                <Label htmlFor="autoApproveFirstEmails" className="font-normal">
                  Auto-approve first emails when drafted automatically
                </Label>
                <p className="text-xs text-neutral-500">
                  Only applies to drafts generated by the automatic
                  auto-draft trigger above — manually clicking
                  &quot;Generate Drafts&quot; or &quot;Regenerate&quot;
                  always leaves a draft for you to review.
                </p>
              </div>
            </div>
            <div className="flex items-start gap-2">
              <Checkbox
                id="autoApproveFollowUps"
                name="autoApproveFollowUps"
                defaultChecked={settings.autoApproveFollowUps}
                className="mt-0.5"
              />
              <div>
                <Label htmlFor="autoApproveFollowUps" className="font-normal">
                  Auto-approve and send follow-ups (skip manual review)
                </Label>
                <p className="text-xs text-neutral-500">
                  Only affects follow-ups that were already generated —
                  first emails always require manual approval regardless of
                  this setting.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-sm font-semibold">
              Follow-up cadence
            </CardTitle>
          </CardHeader>
          <CardContent className="max-w-md space-y-5">
            <div className="space-y-1.5">
              <Label htmlFor="followUp1DelayDays">
                Follow-up 1 delay (days after first email)
              </Label>
              <Input
                id="followUp1DelayDays"
                name="followUp1DelayDays"
                type="number"
                min={1}
                defaultValue={settings.followUp1DelayDays}
                required
              />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="followUp2DelayDays">
                Follow-up 2 delay (days after follow-up 1)
              </Label>
              <Input
                id="followUp2DelayDays"
                name="followUp2DelayDays"
                type="number"
                min={1}
                defaultValue={settings.followUp2DelayDays}
                required
              />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="sequenceLength">
                Sequence length (total touches, including first email)
              </Label>
              <Input
                id="sequenceLength"
                name="sequenceLength"
                type="number"
                min={1}
                max={10}
                defaultValue={settings.sequenceLength}
                required
              />
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-sm font-semibold">
              Email signature
            </CardTitle>
            <p className="text-xs text-neutral-500">
              Appended to the bottom of every email this app sends —
              first touches and follow-ups alike.
            </p>
          </CardHeader>
          <CardContent className="max-w-md">
            <Textarea
              id="emailSignature"
              name="emailSignature"
              rows={5}
              placeholder={"Dave Lakhter\nDallas Global Agency\ndave@dallasglobal.com"}
              defaultValue={settings.emailSignature ?? ""}
            />
          </CardContent>
        </Card>

        <Button type="submit">Save settings</Button>
      </form>
    </div>
  );
}
