-- AlterTable
ALTER TABLE "Email" ADD COLUMN "openedAt" TIMESTAMP(3);
ALTER TABLE "Email" ADD COLUMN "openCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Email" ADD COLUMN "clickedAt" TIMESTAMP(3);
ALTER TABLE "Email" ADD COLUMN "clickCount" INTEGER NOT NULL DEFAULT 0;
